matt-kempster/m2c

src/flow_graph.py, src/if_statements.py
It was painful, and the implementation isn't pretty, but && and || -- at least in their simplest forms -- tend to work now.
=>  Complete handling of && and || in if-statements

src/flow_graph.py, src/parse_instruction.py, src/translate.py
I don't know how I ever managed without mypy. This PR will need a small update after #3.
=> More static types

src/translate.py
Includes the fix from #3 to avoid some annoying merge conflicts, so this needs to be merged after that one.
=> Support some more instructions

.pre-commit-config.yaml, README.md, src/flow_graph.py, src/if_statements.py, src/main.py, src/parse_file.py, src/parse_instruction.py, src/translate.py, tests/fixup-lohi.py
To get this all to work, just `pip install pre-commit black`, making sure you can `which pre-commit` and `which black`.
Use `black .` to autoformat all code manually, or let `pre-commit` handle it for you at commit time.
Shrug. We don't have to do this, but I like black :)
=> Use black to autoformat codebase and add pre-commit config

src/if_statements.py
Especially in the case of loops. the existing code based on comparing indices does not work in that case.
=> various fixes to the postdominator algorithm

src/parse_instruction.py
=> Adding 'j' to branch instructions

src/translate.py
[Trello card](https://trello.com/c/0r3GPRGE/133-allow-using-subroutineargs-as-normal-sps) + some small discussion [on discord](https://discord.com/channels/688807550715560050/703351323445428306/849010792283111445).
- GCC & IDO arrange locals & saved regs differently within the stack frame.
- GCC puts locals below the saved regs, IDO puts them above.
- It's very easy to determine the boundary of the saved regs region in a single pass, so we were previously using that to distinguish between local variables and subroutine arguments by assuming that anything *below* the saved regs was a subroutine arg.
- The new heuristc for detecting subroutine argument boundary also improves output from IDO-compiled asm. It is now better at correctly guessing the number of arguments to functions with >4 …
=> Support GCC by allowing locals above saved registers

src/translate.py
Move the `late_unwrap(self.left)` earlier in the function, and also unwrap `self.right`. 
Ran this commit against OOT & MM (without context), 60/2606 files had diffs, [logs here](https://gist.github.com/zbanks/4bbdef134bc9ae48cb20e532d6906302).
I didn't examine every single diff, but looking a dozen or so closely + skimming the whole file, everything looks good. The most common change seems to be from the comparison inversion.
=> In BinaryOp.format, late_unwrap exprs before checking for Literals

src/translate.py
[Diffs](https://gist.github.com/zbanks/fde5ad2ccd56e42186dbd44aa88fba17)
This helps avoid some temps by skipping over `AddressOf(StructAccess(...))` and `AddressOf(ArrayAccess(...))` in `prevent_later_reads()` and `is_trivial_expression()`.
=> Do not treat AddressOf(StructAccess(...)) as a memory access

src/translate.py
Last PR of the day! :sweat_smile: Some more code I had stashed. 
This closes [this ticket on Trello](https://trello.com/c/R2aPq4AG/63-pass-this-actor-instead-of-actor-this).  When casting to a pointer type, `as_type` checks if it can get the pointer type from a subfield on `expr`. This leads to improvements like:
```diff
-    Actor_SetScale((Actor *) this, 0.01f);
+    Actor_SetScale(&this->actor, 0.01f);
```
[Full diff for MM + OOT](https://gist.github.com/zbanks/6bea1d89695a4e4e2bc28eb0a0c47acd). Nothing too surprising...
There are a few functions which whose deduced types were changed from `void func_80C17468(void **arg0);` to `void func_80C17468(GraphicsContext **arg0);` which helped produce better code.
=> Detect substruct pointers at offset 0 in as_type()

src/flow_graph.py
I offered to do this a while ago, but I just remembered. I think this makes the patterns easier to read and write, since the syntax is a bit more consistent with familiar ones like regex
=> Swap ? and * meaning for pattern matching

src/translate.py
A blast from the past! (I had forgotten about this branch, see [earlier Discord discussion](https://discord.com/channels/688807550715560050/703351323445428306/905460383698006026))
I fixed up the code so that it has **identical** behavior. 
There were two notable places that needed some "fudging":
- Handling function arguments, starting around old line 4163. Need to explicitly use `RegInfo.__getitem__` instead of `RegInfo.get_raw` if we're going to use the `expr` as an argument.
- Determining where to assign phi nodes, starting around old line 1859. Added the `not meta.force` check because the previous comparison did not unwrap the `ForceVarExpr`. If I omit this, the diffs seem pretty minor; but it feels "safer" to keep the check in.
=> Replace ForceVarExpr with a bit in RegMeta

src/translate.py
=> rudimentary add support for ppc

src/translate.py
The `local_var_writes` dict is used to track the last value written to each location on the stack, and is used to elide register restore statements (i.e. after function calls).
However, if a function is called with a reference to the stack, the function *may* modify the stack and invalidate the value held in this dict.
If this is detected, then clear out the `local_var_writes` dict to disable the register-restore logic.
This implementation is maybe a bit too conservative: it considers expressions like `*(&sp10)` to be a reference. I did [try to fix this](https://github.com/matt-kempster/mips_to_c/commit/142948363e660a6d1b6755de03516daec954d9ca), but I abandoned  it because it had mostly the same output, while adding a lot of complexity & still leaving unhandled edge-cases. …
=> Don't restore registers after a function call with a reference to the stack

src/translate.py
Use the expected `offset` of each function arg to choose the correct arg from `subroutine_args`, and emit an error if it is missing.
Additionally, if the function has `params_known`, it is not necessary to re-unify the parameter types. This was causing frame shift issues when there was a return struct or a >4-byte parameter. This fix causes most of the diffs in the project tests.
[Diffs](https://gist.github.com/zbanks/824e7811836821cca181ed675bbac4c0) (a bit odd that OOT had no diffs, but it's a relatively small corpus)
=> Match stack args to their slots based on offset

.github/workflows/python-app.yml
Tested that this catches formatting errors
=> Add formatting check to github workflow

src/if_statements.py, src/main.py, src/options.py, website.py
before:
```
void func_80240904_9BBBA4(void *arg0, s32 arg1) {
s32 var_v0;
void *temp_v0;
switch (arg1) {                                 /* irregular */
case 0:
if ((arg0->unk0 & 2) == 0) {
arg0->unk10 = (f32) (arg0->unk10 * 0.95f);
return;
}
return;
case 1:
arg0->unk10 = (f32) (arg0->unk10 * 1.12f);
if (arg0->unk20 == 0xA) {
temp_v0 = start_script(&D_80240F2C_9BC1CC, 1, 0);
temp_v0->unk84 = (s32) arg0->unk14;
temp_v0->unk88 = (s32) arg0->unk18;
arg0->unk0 = (s32) (arg0->unk0 | 2);
return;
}
break;
case 2:
var_v0 = arg0->unk2C->unkC;
if (var_v0 < 0) {
var_v0 = -var_v0;
}
arg0->unk10 = (f32) ((f32) var_v0 * signF(-arg0->unk10));
break;
}
}
```
after:
```
switch (arg1) {                                 /* irregular */
case 0:
if ((arg0->unk0 & 2) == 0) {
arg0->unk10 = (f32) (arg0->unk10 * …
```
=> arg for adding extra indentation for switch statements' contents

m2c/asm_file.py
Support disassembly output from encounter's decomp-toolkit
=> Support .fn directive in asm

m2c/main.py, m2c/options.py, m2c/translate.py
Is the way I passed over the option fine?
=> Add option to disable the stack spilling logic

m2c/arch_ppc.py, m2c/evaluate.py
We should update the test results after we merge the comparison PR.
=> Handle rlwnm instruction
