matt-kempster/m2c

- src/parse_file.py
So you can use mips_to_c on functions in files obtained from n64split.
> Add compatibility with n64split's func_XXXXXXXX: notation

- src/if_statements.py
- src/main.py
A very simple PR to make the logic at the bottom of `if_statements.py` return a string instead of printing it out piece by piece. 
Things I considered also doing:
- Putting `get_function_text()` in its own file. It is not the "proper" entry point of if_statements; `get_body()` is. But this file would be pretty sparse - I'm not sure what else would fit there. So I decided against it for now.
- Renaming `if_statements.py` to something like `flatten_flow_graph.py` or `flatten_ast.py` or `ast_to_statements`, since that more accurately represents what it's doing - it's taking a whole bunch of info and outputting a list of statements.
> Refactor the main function of if_statements to return a string

- src/translate.py
- src/types.py
I was interested in improving some of the type detection stuff, and it seemed like a prereq for that was having the `TypeMap` available to the `Type.unify()` function.
There are two calls on the `format` codepath that called `unify`, and it was really hard to get the typemap there. My understanding of the code is that the types should already be resolved at that point -- the `unify` function is mostly a check if the two types are the same. I added a `Type.is_unified()` (`is_equivalent`?) method to start to try to refactor it even though it's a bit ugly.
As mentioned on the Discord, this won't handle all cases: the typemap still isn't available everywhere. I'll need to take another pass at this.
> Attach TypeMap to CType-related Types

- code_coverage.py
- run_tests.py
- src/c_types.py
- src/main.py
- src/parse_file.py
This was discussed briefly on the Discord yesterday. Here are some notes about this PR:
- I'm calling them "project tests" -- not super happy with that name, but had trouble thinking of a better one.
- This PR doesn't commit the results of the tests. There was some brief discussion on the discord about how best to design this so that we can keep this repo isolated from the decomp project repos. 
- I'm personally excited enough to get this code in as-is, even if it's a bit trickier to work with. Even though the "baseline" output `.c` files are not checked in, I can run the tests locally before making changes to populate the `tests/` directory with the baseline files.
- The project tests use `ctx.c` if it exists in the project base directory. This also makes the tests *a lot* slower.
- I …
> Add `--project` flag to run tests against all mm/oot asm

- src/translate.py
- tests/end_to_end/andor_assignment/irix-g-out.c
- tests/end_to_end/doubles/irix-g-mips1-out.c
- tests/end_to_end/doubles/irix-g-out.c
- tests/end_to_end/int-float-doublelit/irix-g-out.c
- tests/end_to_end/int-float/irix-g-out.c
- tests/end_to_end/jump-into-loop/irix-g-out.c
- tests/end_to_end/loop_nested/irix-g-out.c
- tests/end_to_end/loop_with_if/irix-g-out.c
- tests/end_to_end/sqrt/irix-g-out.c
Some notes:
- There are two other places that can emit `lhs = rhs;` statements that I didn't change: `EvalOnceStmt` & `SetPhiStmt`. In these two cases, I don't think it's possible to have `lhs` be in the `rhs` expression. 
- I didn't simplify `x += 1;` into `x++;` to avoid having to deal with precedence rules. (`*x += 1;` is not equivalent to `*x++`).
- IMO refactoring `x += 1;` by hand is still easier to than `x = x + 1;`
- It looks like `late_unwrap(...)` is completely safe to use inside `format(...)` functions. I think `late_unwrap(expr).format(fmt) == expr.format(fmt)` is an invariant.
> Simplify `x = x op y` into `x op= y`

- run_tests.py
In general, this PR just touches `run_tests.py`, so I'm not sure how much it needs to be PR'd, but I'm happy to incorporate any feedback. 
----
- Adds `-j N`/`--parallel=N` argument to `run_tests.py` 
- Test name + output is grouped together and printed from the main thread atomically, to keep the log easy to read & avoid tearing.
- Print test summary at the end w/ # of tests
- Basic test on runtime on my 4-core laptop, `./run_tests.py --project ~/mm`
- Baseline: 183 seconds
- `-j 2`: 92 seconds
- `-j 4`: 58 seconds
- `-j 5`: 58 seconds
> Option to run tests in parallel

- run_tests.py
- src/c_types.py
- tests/end_to_end/complicated_context/irix-o2-typemap-out.c
~~Is it related to this `deepcopy` call?~~
The issue was that ` type_to_string` was calling `set_decl_name` without deepcopy'ing `type`. This mutated the `typemap` state, which is cached & re-used between tests. This appears to be the only place where `typemap` is mutated, so it should be sufficient.
The new test output looks more correct - it consistently has the arg/field names.
I also sorted the tests as an independent change, to make the output more consistent across machines.
> Fix test nondeterminism

- src/main.py
- src/options.py
- src/translate.py
- tests/end_to_end/array-access/irix-g-flags.txt
- tests/end_to_end/array-access/irix-g-out.c
- tests/end_to_end/array-access/irix-o2-flags.txt
- tests/end_to_end/array-access/irix-o2-out.c
- tests/end_to_end/complicated_context/irix-g-flags.txt
- tests/end_to_end/complicated_context/irix-o2-flags.txt
- tests/end_to_end/function-pointer2/irix-o2-flags.txt
- tests/end_to_end/function-pointer2/irix-o2-out.c
- tests/end_to_end/misc1/irix-o2-validsyntax-flags.txt
- tests/end_to_end/misc1/irix-o2-validsyntax-out.c
- Created a `GlobalInfo` class for managing any (potentially mutable) cross-function state.
- Right now this is the TypeMap, Rodata, and types of global symbols
- Happy to have a better name, it felt like a good complement to `FunctionInfo`?
- Added `--emit-globals` flag, making the default behavior to *not* print these detected globals.
- I think it'd be nice to make this on by default once there's a chance for it to "burn in" for a bit, and #106 is merged which will fix global function decls which currently show up as `void *` or `? *`.
- Added `--emit-globals` to a smattering of existing tests
- Without modifying the test flags, there is no change in test output.
> Add GlobalInfo class for managing top-level declarations

- src/translate.py
- src/types.py
Having the only accessor for TypeData do get_representative prevents bugs.
> Split out TypeData from Type

- src/translate.py
- src/types.py
This PR mostly resolves that TODO I had left open from my previous PR.
```
```
- Now `FunctionSignature.unify()` does that ^
- Added an explicit note about how a function type without `params_known` can have its *number* of parameters change over time: this can result in early calls having fewer arguments than the eventually determined type. I added a warning about this to `FuncCall.format()`
- An interesting idea is to try to patch these calls up at a later time: either remove args, or add args from the `possible_regs` candidates that were previously discarded. I think this is tricky to do right; doing it at format-time would make `FuncCall.dependencies()` unreliable.
- On the plus side, this seems pretty rare and the errors aren't too bad for a human to patch. (It is also fixable by …
> Improve function type unification

- run_tests.py
- src/flow_graph.py
- src/main.py
- src/options.py
- src/parse_file.py
- src/translate.py
This PR has a lot of lines changed, but it's mostly renaming. The technical aspects are pretty small, I wanted to check that the renaming I did makes sense.
- `Rodata` --> `DataSection`, which now holds `.rodata`, `.data`, and `.bss`. (although `.bss` is untested)
- `RodataEntry` --> `DataSectionEntry`, which has a `is_readonly` attr for distinguishing rodata from data/bss.
- Changed the command line arg `--rodata` to `--data` & updated help/error messages. Left in support for `--rodata` as a hidden option to preserve compatibility.
> Support loading in .data & .bss in addition to .rodata

- mips2c_macros.h
- src/main.py
- src/translate.py
- src/types.py
- tests/end_to_end/function-pointer2/irix-o2-out.c
- tests/end_to_end/global_decls/irix-o2-flags.txt
- tests/end_to_end/global_decls/irix-o2-out.c
- tests/end_to_end/global_decls/irix-o2.s
- tests/end_to_end/global_decls/orig.c
- tests/end_to_end/misc1/irix-o2-validsyntax-out.c
- When a function fails to decompile, wrap the error message/traceback in `/* ... */` so that you can still try to compile the output.
- I considered only doing this when `--valid-syntax` is enabled, but it seems benign?
- Added new `MIPS2C` macros for unaligned reads. Rearranged existing macros to be in order of "most-to-least common" to be easier to read.
- ~~Use `/* ... */` for comments, because IDO/c89 does not support `//`~~
- `GlobalInfo` now handles `.global_symbol(...)` and `.address_of_gsym()`
- Expose more information in the `global_decls()` section.
- If a function is marked `/* extern */`, this means it should be defined in a common header file.
- Indicate when variables in file scope look like arrays.
- For simple types, generate the initializer. 
---
I tried directly …
> Improve global_decls() for C-like output

- src/flow_graph.py
- src/main.py
Small change!
Not sure if anyone had attachments to the previous flow graph format. If the blocks have not been translated, then it produces very similar output to the old format (except the nodes are rectangles with `// Node N`)
The code in the blocks is not perfect -- it's based solely on the steps from `translate_to_ast()` (before any `if_statements.py`). It still helps to get an approximation of what each branch represents though.
Here's an example from OOT's `ovl_En_Dekubaba/func_809E80D8.s` of what it looks like now - it's a bit easier to follow what's going on.
> Show code, if available, in `--visualize` flow graph

- run_tests.py
- src/flow_graph.py
- src/if_statements.py
- tests/end_to_end/andor_assignment/irix-o2-noandor-out.c
- tests/end_to_end/andor_mixed/irix-g-out.c
- tests/end_to_end/andor_mixed/irix-o2-out.c
- tests/end_to_end/andor_return/irix-g-out.c
- tests/end_to_end/andor_return/irix-o2-out.c
- tests/end_to_end/doubles/irix-o2-mips1-out.c
- tests/end_to_end/loop/irix-o2-out.c
- tests/end_to_end/loop_nested/irix-o2-out.c
- tests/end_to_end/multi-switch/irix-o2-out.c
- tests/end_to_end/nested_ifs/irix-o2-out.c
- tests/end_to_end/nested_ifs2/irix-o2-out.c
- tests/end_to_end/nested_ifs3/irix-o2-out.c
- tests/end_to_end/nested_ifs4/irix-g-out.c
- tests/end_to_end/nested_ifs4/irix-o2-out.c
- tests/end_to_end/switch-with-if/irix-o2-out.c
- tests/end_to_end/switch/irix-g-out.c
- tests/end_to_end/switch/irix-o2-andor-out.c
- tests/end_to_end/switch/irix-o2-out.c
In order by commits. The tests were re-blessed after each change, so you can see the results of each code change.
- Fix `run_tests.py` to find rodata/data for Paper Mario
- Now papermario tests pass that depend on rodata, like `func_8013AA9C`, don't error out. (This doesn't show up in the repo though)
- `if (A) { B; } else { goto C; }` --> `if (!A) { goto C; } B;`
- Could be `goto C;` or `return C;` -- as long as the body ends in a jump.
- Output structure changes in some cases; `B` clause unindented by one.
- The `andor-mixed` test (and `render_models` in Paper Mario) have (imo) more readable flow with `if (...) { goto ...; }` up front. The `goto`s are all now _forward_ jumps in the C source.
- I pushed some logic out of `Body.add_if_else()` into `IfElseStatement.format()` because it …
> 3 cleanup tasks (flowgraph/tests)

- src/types.py
- tests/end_to_end/recursive-type/irix-g-out.c
- tests/end_to_end/recursive-type/irix-g.s
- tests/end_to_end/recursive-type/irix-o2-out.c
- tests/end_to_end/recursive-type/irix-o2.s
- tests/end_to_end/recursive-type/orig.c
Fixes #81 and [Trello](https://trello.com/c/Z8ZhygMP/51-type-unification-can-recurse-forever).
The motivation for fixing this was the IDO recomp project, trying to run `./mips_to_c.py` on `uopt.s` from that lead to a *bunch* of these errors. After this PR IDO's `uopt.s` decompiles without `RecursionError` -- it only has 4 errors over the whole file.
Between the other projects (OOT, MM, PM), the only file that hit a `RecursionError` was MM's `boot/fault.asm` when run without context.
I made `Type.unify()` just give up if it detects any amount of recursion. In theory, there may be certain cases where it *could* succeed? 
I could forsee needing a more robust solution if we implemented "pure" `Type` representations of structs: but for now, recursive structs like `struct foo { struct foo * x; …
> Prevent `Type.unify()` from recursing forever

- run_tests.py
- src/flow_graph.py
- src/main.py
- src/options.py
[Trello ticket](https://trello.com/c/toC3va4m/137-improve-cli-to-support-multiple-input-output-files)
- Add argument groups, to make `--help` easier to read
- New (preferred) format is `./mips_to_c.py -f fn -f fn asm.s asm2.s ...`
- Detect if the last argument is "function-like", to keep compatible (no breaking changes, unless there's a bug)
In discord there was talk of`./mips_to_c.py files+ functions*`; but this PR encourages `./mips_to_c.py files+ (-f function)*` and supports `./mips_to_c.py files+ function?` for backwards compatibility. I did this because it seemed less fragile, but still good UX? I could easily change it to `files+ functions*` though without the `-f` instead, if that's preferred.
I rearranged the args to put them in some top-level groups, but I know the diff is tricky …
> Refactor CLI (while maintaining compatability)

- src/flow_graph.py
- src/main.py
- src/options.py
- src/types.py
- tests/end_to_end/known_called_function/irix-g-flags.txt
- tests/end_to_end/known_called_function/irix-g-out.c
This PR adds a new runtime flag which allows the user to configure pointers to be next to the type name rather than the variable name. Default behavior is unchanged.
> Support for "left-style" pointers with new --pointer-style option

- .github/workflows/python-app.yml
- README.md
- run_tests.py
- src/c_types.py
- src/error.py
- src/flow_graph.py
- src/if_statements.py
- src/options.py
- src/parse_file.py
- src/parse_instruction.py
- src/translate.py
- src/types.py
Something weird is happening with
```
@dataclass(frozen=True, eq=False)
class RegisterVar(Expression):
type: Type
register: Register
```
where if the two fields swap places there's an error
```
Traceback (most recent call last):
File "./mips_to_c.py", line 2, in <module>
from src.main import main
File "./mips_to_c/src/main.py", line 11, in <module>
from .if_statements import get_function_text
File "./mips_to_c/src/if_statements.py", line 15, in <module>
from .translate import (
File "./mips_to_c/src/translate.py", line 948, in <module>
class RegisterVar(Expression):
File "/usr/lib/python3.7/dataclasses.py", line 1002, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
File "/usr/lib/python3.7/dataclasses.py", line 921, in _process_class
globals,
File …
```
> Use dataclasses instead of attrs

- src/flow_graph.py
- src/main.py
- website.py
- "Visualize" button that renders an SVG (requires graphviz)
- Do you have `graphviz` installed on the server?
- @simonlindholm Are you OK with the security implications of this? The library's render operations all shell out to a graphviz executable. I could remove this, or have it disabled in `website.py` unless an environment variable is set?
- Checkbox for `--emit-globals`, enabled by default
- Dropdown for selecting function to decomp, default to `all`. (Before it would decomp the first function defined)
- There's a regex in JS to pick out function names from the assembly, looking for "glabel". It has a lot of false positives (all variable labels), but I think it's an improvement?
> Website features

- src/c_types.py
- src/options.py
- src/translate.py
- src/types.py
- tests/end_to_end/global_decls/irix-o2-out.c
- tests/end_to_end/global_decls/irix-o2.s
- tests/end_to_end/global_decls/orig.c
I had to fix one more underlying bug, where multidimensional arrays were not handled correctly. They would be repeatedly pointer-decayed down to their inner type, losing the intermediate dimensions.
The output of running this fix (`c5f411a`) against MM with context is [here](https://gist.github.com/zbanks/1fcd76417568f3757e8186bf37c50840). 
- Most of the differences are to matrix functions which take `float (*m)[4]`s as arguments instead of matrix structs. 
- Some matrix stack variables were previously (incorrectly) inferred to be `f32`, but are now marked as `?`. This doesn't seem too bad to me -- it's arguably more accurate?
- The first diff, `guMtxIdentF`, is a slight regression because mips2c is not able to deduce that the RHS of the assignments are floats. This appears to be pretty …
> CType initializers

- src/translate.py
- tests/end_to_end/branch-likely-b/manual-out.c
- tests/end_to_end/branch-likely-one-instruction/manual-out.c
- tests/end_to_end/global_decls/irix-o2-out.c
- tests/end_to_end/loop/irix-g-out.c
- tests/end_to_end/loop/irix-o2-out.c
- tests/end_to_end/misc1/irix-g-out.c
- tests/end_to_end/misc1/irix-o2-out.c
- tests/end_to_end/misc1/irix-o2-validsyntax-out.c
- tests/end_to_end/phis-1/manual-out.c
(As discussed on Discord.)
Output from running tests against MM w/ context is [here](https://gist.github.com/zbanks/00b946953f767fa8c5a4af8a89abdf64).
One downside that we hadn't talked about yet is that all pointer casts used to be `(void *)`, regardless of pointer type. There are some places where we know it's a pointer, but we don't know the exact type, so it now shows up as `(? *)` or `(?32 *)`. 
I think this is still an improvement? I don't think `*(void *)0xA02FE1C0` is much better than `*(? *)0xA02FE1C0`: neither is valid C, and at least the latter is formatted as `*(MIPS2C_UNK32 *)...` with `--valid-syntax`.
> Remove integer casts for Literals

- src/if_statements.py
- tests/end_to_end/andor_assignment/irix-o2-noandor-out.c
- tests/end_to_end/andor_loops/irix-g-out.c
- tests/end_to_end/andor_loops/irix-o2-out.c
- tests/end_to_end/andor_mixed/irix-g-out.c
- tests/end_to_end/andor_mixed/irix-o2-out.c
- tests/end_to_end/break/irix-g-out.c
- tests/end_to_end/break/irix-o2-out.c
- tests/end_to_end/doubles/irix-o2-mips1-out.c
- tests/end_to_end/loop/irix-o2-out.c
- tests/end_to_end/loop_nested/irix-o2-out.c
- tests/end_to_end/multi-switch/irix-o2-out.c
- tests/end_to_end/switch-with-if/irix-o2-out.c
- tests/end_to_end/switch/irix-g-out.c
- tests/end_to_end/switch/irix-o2-andor-out.c
- tests/end_to_end/switch/irix-o2-out.c
Mentioned in the Discord - but this seems like a weird trick that should smooth out some of the nesting that has been happening since my flowgraph refactor, particularly around switch statements. 
This works by making `goto`s in if/else blocks prefer jumping *forward* (from `if` to `else`), rather than *backwards*.
One potential downside is the way that loops are emitted: the previous version was biased towards `continue;`s (which jump backwards), and it seems this version emits better codes for `break;`s?
As a side effect, I also needed to precompute switch indexes so they wouldn't be reversed.
Example from MM: `EnZoraegg_Init`, which has two switch statements (not a multi switch) and the first has early returns: https://gist.github.com/zbanks/d26f7de31be4e3a85e57d93e9ec9ccf6
> Improve early return handling by swapping the order if/else blocks are built

- src/translate.py
- tests/end_to_end/andor_assignment/irix-o2-noandor-out.c
- tests/end_to_end/andor_assignment/irix-o2-out.c
- tests/end_to_end/andor_loops/irix-o2-out.c
- tests/end_to_end/andor_mixed/irix-o2-out.c
- tests/end_to_end/break/irix-o2-out.c
- tests/end_to_end/loop/irix-o2-out.c
- tests/end_to_end/loop_nested/irix-o2-out.c
- tests/end_to_end/loop_with_if/irix-o2-allman-out.c
- tests/end_to_end/loop_with_if/irix-o2-out.c
- tests/end_to_end/multi-switch/irix-o2-out.c
- tests/end_to_end/multiple-assigns/irix-o2-out.c
- tests/end_to_end/switch/irix-g-out.c
- tests/end_to_end/switch/irix-o2-andor-out.c
- tests/end_to_end/switch/irix-o2-out.c
In `assign_phis()`, rather than emit the `SetPhiStmt` at the end of each of parents, try to find a different set of nodes that has equivalent behavior, but will likely produce nicer code.
- Prefer picking *earlier* nodes when possible. This helps avoid getting assignments inside complex conditionals (see `andor` tests), and can result in similar phi nodes "bunching up" in a way that's easier to refactor (see `phi_a0_2`-`5` in `multi-switch` test).
- If two or more of `phi.node.parents` share a dominator, we can do the assignment *once* in the dominator, as long as the value of the register at that node is the same. This reduces the number of statements.
- I originally thought loops would be tricky. I was worried we needed to avoid moving phi assignments out of loops, because that's not …
> Improve phi assignment by picking an earlier/smaller set of nodes for SetPhiStmt

- src/flow_graph.py
- src/if_statements.py
- src/translate.py
- tests/end_to_end/multi-switch/irix-o2-out.c
- tests/end_to_end/switch-with-if/irix-o2-out.c
- tests/end_to_end/switch-with-if/irix-o2.s
- tests/end_to_end/switch/irix-g-out.c
- tests/end_to_end/switch/irix-o2-andor-out.c
- tests/end_to_end/switch/irix-o2-out.c
Most switches are proceeded by a `ConditionalNode` which performs a bounds check to ensure that the jump table access is valid. This check is pretty consistent across IDO/GCC. 
It's straightforward to combine this check with the `switch (...)` statement itself: if the conditional branch indicates the default case. (If the conditional branch is to `end`, that indicates that there is *no* default case).
This change was enabled by the earlier phi PR. There used to frequently be phi assignment expressions at the top of `SwitchNode`s, which makes it hard to combine the if+switch. Now those are almost entirely gone, so this heuristic is drastically more successful.
---
I tested this across OOT, MM, & PM (without context). It was able successfully combine 1045 instances, and only failed at 13. …
> Detect and combine "if guards" with switches

- src/flow_graph.py
- src/if_statements.py
- tests/end_to_end/known_called_function/irix-g-out.c
- tests/end_to_end/known_called_function/irix-o2-out.c
- tests/end_to_end/loop-selfassign-phi/irix-g-out.c
- tests/end_to_end/loop-selfassign-phi/irix-o2-out.c
- tests/end_to_end/return-detection/floats-out.c
- tests/end_to_end/return-detection/read-fncall-out.c
- tests/end_to_end/unreachable-return/irix-g-out.c
- tests/end_to_end/unreachable-return/irix-o2-out.c
This is sort of a hack? I definitely want feedback on this, maybe it's *too* hacky?
The idea is to find nodes which cannot reach the TerminalNode (i.e. infinite loops) and add a "fake" edge to the TerminalNode. This edge is used by `compute_relations(...)`, but then is ignored by `build_flowgraph_between(...)`. 
This change fixed 190 functions across OOT/MM/PM (183 of them from PM). 
There are only 4 functions left in PM, plus 2 end-to-end tests, which still have the "Flowgraph is not reducible..." warning. These functions cannot be made reducible by adding new edges (they would need to split nodes).
> Add fake edges to the flow graph to break infinite loops and make the graph reducible

- src/translate.py
- tests/end_to_end/andor_assignment/irix-o2-noandor-out.c
- tests/end_to_end/andor_assignment/irix-o2-out.c
This seems to fix the issue mzx was having in Discord with function `func_800CA22C` from MM, where `phi_a0_2` was uninitialized.
It looks like there was a similar bug in the e2e test for `andor_assignment` - so there's already test coverage for this fix.
I don't have a good enough understanding of the phi machinery to succinctly explain why this fixes the problem: but, I don't think this change invalidates any existing comments. If you have any suggestions for updating them to be more clear/explicit let me know. 
This problem predates my earlier PR #135 that changed where phi assignments were handled.
> Check `phi.replacement_expr` in `PhiExpr.propagates_to()`

- src/types.py
I'm working on [pass `&this->actor` instead of `(Actor*) this`](https://trello.com/c/R2aPq4AG/63-pass-this-actor-instead-of-actor-this) but was getting some bad field inferences.
[Diff for OOT/MM](https://gist.github.com/zbanks/238500a7b39ec8c62642c14fc0fc3acb). The diffs aren't *great* -- most of the changes look like the type from the context is either wrong, or part of a union. But, the intent is to completely trust the context-provided types.
> Use target_size to avoid creating overlapping fields

- src/flow_graph.py
- src/if_statements.py
- src/main.py
- src/options.py
- src/translate.py
- tests/end_to_end/recursive-type/irix-g-out.c
- tests/end_to_end/recursive-type/irix-o2-out.c
This generally improves type inference, but causes mips_to_c to run slower. More than 2 seems to not make a difference for single-function decomps.
`--passes=1` is the old behavior, `--passes=2` is the new default behavior and is about 50% slower than before (this trend is approximately linear afaict).
[Diffs from OOT, MM, PM](https://gist.github.com/zbanks/5f6fa0dfb278aa6674e684ba0e451504). Sorry that they are too large for github to display inline. There are a few that are worse where there was some incorrect struct type inference: this isn't great, but it should be relatively straightforward to identify & correct manually?
> Add --passes/-P for running multiple passes over the input

- src/translate.py
- src/types.py
This is a relatively small change, but I think it improves the output a lot (at least on PM/MM). As I mentioned on discord, I know I have a lot of PRs open right now, but this change seems more useful than the others?
The "weird" part, IMO, is where I create a new struct when `x` is a `GlobalSymbol` and `scale` isn't 1, 2, or 4. This has the downside of potentially being wrong/noisy, because the new struct can't then unify with an existing struct. However, I think it has a net positive on the output? And it hopefully it's easy for the decomper to look at, and quickly identify "these look like the same struct" or "this looks like a `Vec3s`".
The output also has a lot more expressions like `(&sp30)[...]`, because stack variables are not yet allowed to be arrays. The element type is usually …
> Use `&x + scale * index` expressions to determine `x`'s type

- src/main.py
- src/types.py
This PR adds a pass that cleans up inferred fields in structs. This pass can change the paths used in `StructAccess`/`LocalVar` expressions, so it's only run when there are multiple passes. 
This primarily solves two problems:
1. Overlapping fields which are actually subfields of an earlier field. 
- In `Vec3f unk0; f32 unk4; f32 unk8;`, `unk4` is really `unk0.y` and can be deleted.
- This is an issue I had wanted to fix before allowing stack vars to be structs.
2. Incorrectly inferring large structs. 
- It was really common to incorrectly infer `Actor unk_144;` in MM structs. This was brought up in #172. 
- I think most of these errors are caused by missing arguments in function calls, but they're relatively easy to fix while fixing 1. This PR is more of a band-aid for these types of …
> Prune overlapping struct fields in preliminary passes

- src/translate.py
This adds support for the following instructions:
- `mulli`: 32-bit multiplication
- `lwzx`, `lhzx`, `lbzx`: register-indexed load instructions
Example input:
```
.global ARCChangeDir
ARCChangeDir:
/* 80210EEC 00206C6C  94 21 FF F0 */	stwu r1, -0x10(r1)
/* 80210EF0 00206C70  7C 08 02 A6 */	mflr r0
/* 80210EF4 00206C74  90 01 00 14 */	stw r0, 0x14(r1)
/* 80210EF8 00206C78  93 E1 00 0C */	stw r31, 0xc(r1)
/* 80210EFC 00206C7C  7C 7F 1B 78 */	mr r31, r3
/* 80210F00 00206C80  4B FF FB 9D */	bl ARCConvertPathToEntrynum
/* 80210F04 00206C84  2C 03 00 00 */	cmpwi r3, 0
/* 80210F08 00206C88  80 9F 00 04 */	lwz r4, 4(r31)
/* 80210F0C 00206C8C  41 80 00 14 */	blt lbl_80210F20
/* 80210F10 00206C90  1C 03 00 0C */	mulli r0, r3, 0xc
/* 80210F14 00206C94  7C 04 00 2E */	lwzx r0, r4, r0
/* 80210F18 …
```
> PPC: Support `mulli` and `lwzx`, `lhzx`, `lbzx` instructions

- src/main.py
- src/options.py
- src/parse_file.py
- Cherry-pick'd `069f226` from `ppc2cpp`
- Removed the `-I` shortarg for `--incbin-dir`, not sure if we really want to use `-I` for that.
- Refactored directive parsing in `parse_file`to avoid manual string slicing.
- Checked that the new `parse_file.py` can be used on the `ppc2cpp` branch without additional modifications.
- All tests still run, no diffs in OOT, MM, or PM.
> Cherry-pick changes to parse_file.py from ppc2cpp branch + cleanup

- src/arch_mips.py
- src/main.py
- src/translate.py
Happy to take any feedback here, now is a great time to make name changes or do any restructuring.
Potential weird things:
- I put the new `Arch` on `GlobalInfo`, but maybe it should also be in `Options`? Or only in `Options`? (Maybe `Options` should be available in more fns)
- I use a singleton instance of `MipsArch()`, instead of passing the class itself around. This *feels* like it would play better with the type system, but I'm not actually sure?
> Move MIPS instruction handling to a new python file

- src/translate.py
- tests/end_to_end/complicated_context/irix-g-out.c
- tests/end_to_end/complicated_context/irix-o2-out.c
- tests/end_to_end/gcc-division/gcc-o2-out.c
Follow-up to Simon's suggestion in #198.
For large arguments that span multiple `AbiArgSlot`s, add inline comments indicating their type & offset. This is done using a new `CommentExpr` wrapper. I also changed the argument names to add the `_unk0` if the argument does not fit in one slot, instead of starting with `_unk4`.
Warn when there are unused `subroutine_args` for functions with known parameters by including an `extra?` comment.
[Diffs](https://gist.github.com/zbanks/c26b1658f1050eaf3db48c0592214ce6)
- The `/* extra? */`s for `create_entity` in PM are false positives: the prototype in my context file does not have an ellipsis, unlike the `main` branch.
- I'm not sure how these arguments should interact with `StackInfo.add_known_param(...)` -- what type should be used when an …
> Add comments when args span multiple slots

- src/arch_mips.py
- src/translate.py
- Move `function_abi(...)` into the new `Arch` class
- Add `likely_regs` arg to move the `possible_regs` loop into this function -- the logic around `Register("f13")` is hard to abstract in a clean way otherwise, imo.
- It'd be possible to also pass the function's `symbol_name`, the state of `subroutine_args`, or the state of `cr1_gt` (the PPC bit that is related to float varargs) -- but I'm just adding what's used for now.
- Use `function_abi(...)` to set initial register states at the start of `translate_to_ast(...)`
- Minor difference: now includes both `$f13` and `$f14` at "offset 4", instead of just `$f14`. It's a little weird, I guess? It doesn't seem particularly better/worse than what we were guessing before?
- Moved setting the return registers into a new `function_return(...)` …
> Move ABI-related functions into arch_mips.py

- src/arch_mips.py
- src/flow_graph.py
- src/main.py
- src/parse_file.py
- src/parse_instruction.py
- src/translate.py
This PR has no (intentional!) functional changes; it is just moving the methods out of `Instruction` and into the new `ArchAsm` ABC. This is to prepare for incorporating PPC support from the `ppc2cpp` branch.
`Arch` is now a "super-interface" that also implements `ArchAsm`, so `MipsArch` implements *both* the translate-related behaviors *and* the instruction-related functions. 
I opted to pass `arch: ArchAsm` around to a lot of the functions in `flow_graph` -- the alternative would be to add it as a member to `Function`, but that felt inelegant?
> Refactor `Arch` & `Instruction`, create `ArchAsm` ABC

- run_tests.py
- src/arch_mips.py
- src/flow_graph.py
- src/if_statements.py
- src/parse_file.py
- src/parse_instruction.py
- src/translate.py
This is a bunch of small changes which have little-to-no effect on the existing behavior, but can bring the main branch closer to `ppc2cpp`.
- ArchAsm: add `all_regs` & `aliased_regs`
- ArchAsm: make `frame_pointer_reg` optional
- ArchAsm: add additional fns
- Arch: set defaults for `instrs_*`
- Refactor `handle_ori()` to `handle_or()`
- Change `Node` debug reps to prefer `.name()` over `.block.index`
- Emit skipped nodes in stable order
- Use `ArchAsm` for more instruction parsing (`.all_regs`)
- Allow `$` in symbol names
- Allow `;` as a comment separator, like `#`
- Remove trailing space from zero-argument `Instruction`s
- Add project support to `run_tests.py`
----
Only diffs are from `MIPS2C_ERROR`'s when the instruction has zero arguments, like the following:
```diff
[INFO] Output of …
```
> More preparation for `ppc2cpp` merge

- src/arch_mips.py
- src/arch_ppc.py
- src/asm_pattern.py
- src/flow_graph.py
- src/parse_instruction.py
- src/translate.py
Add arch-specific information to each `Instruction` that describes how it should be interpreted.
This replaces the existing `ArchAsm.is_*_instruction(...)` functions by including this information directly inside the `Instruction` object.
`AsmInstruction` is introduced to represent a "raw" instruction, with just a mnemonic + args.
This PR doesn't change any behavior (that I'm aware of); it's a refactor to help with more complex pattern matching that I'm working on. Project & end-to-end tests still pass: tested MIPS with MM, PM; tested PPC with Melee, SMS, and SMB1.
The first commit (`036e579`) is equivalent to [the changes I posted in Discord](https://github.com/matt-kempster/mips_to_c/compare/master...zbanks:8c9394e), to help make re-reviewing a bit easier.
> Refactor `Instruction` to include arch information

- src/translate.py
- src/types.py
I think after #178, this is viable now? 
[Diffs in OOT/MM/PM](https://gist.github.com/zbanks/cc88f4a0c348c465b0cf13b9247fbb7b)
- I carefully looked at the first 5% of MM, then skimmed the next ~15%, then very quickly skimmed the remainder.
- I skimmed OOT, it looked pretty similar to MM
- I skimmed PM, it's mostly less interesting because it uses structs less (mostly matrices/vectors)
There are some minor issues in the diffs, but I don't consider them regressions. (I'd also rather fix them in separate PRs to avoid changing too much at once?)
- [(example: MM lines 200-203)](https://gist.github.com/zbanks/cc88f4a0c348c465b0cf13b9247fbb7b#file-mm-diff-L200-L203) Arrays can show up as `u8 spN[]; char pad[0x10];` instead of `u8 spN[0x10];`. 
- It should be straightforward to add a pass that …
> Allow struct types on the stack

- src/arch_mips.py
- src/arch_ppc.py
- src/parse_instruction.py
Previously, since `fp` is the name of a MIPS register, this would be incorrectly parsed as `Macro("hi", Register("fp"))`.
This change disables the sigil-less register coercion when parsing `Macro` or `BinOp` expressions.
> Parse args like `%hi(fp)` where `fp` is a symbol

- src/parse_instruction.py
- src/translate.py
These were not being converted properly, so changed the function call to translate the name correctly. Behaviour is currently to silently use the names from the assembly rather than whatever the user specified. Possibly a note should be generated at output to explain this if it arises, but it would require modifying the parsing functions a fair amount, I imagine.
> Fix reg_vars behaviour for individual register names

- src/parse_file.py
- src/parse_instruction.py
- src/types.py
This PR is a combination of a few small fixes:
- Prune inferred fields in structs that exceed the (known) size of the struct itself.
- [Diff for N64 projects](https://gist.github.com/zbanks/56826ed69047b6cd25fdbb9ca36b5c36) -- prevents issues like including a whole `Actor` or `GlobalContext` inside a smaller struct.
- Handle quoted symbols individually when parsing asm arguments, to parse terms like `"foo<bar>@baz"@ha`
- Still use `csv` to parse asm directives in `parse_file.py`, but consolidate the `.strip()` operations.
- Allow `0` to symbolize the zero register in AsmAddressMode, like in `lwz r4, 0xc0(0)`
- Handle `.if 0` and `.if 1` directives instead of skipping them
> Improve asm file parsing; prune oversized structs

- src/translate.py
The previous pattern for detecting mod operations was limited to taking the mod of a `Literal` constant.
However, PPC has no mod instruction, so mod is implemented using the same series of instructions that GCC uses to mod by a constant in MIPS, `x % y` becomes `(x - ((x / y) * y))`.
This change produces no diff in any of the MIPS project corpuses, but makes several improvements to the PPC ones.
[Diff in the SMS project](https://gist.github.com/zbanks/5adcd36cabc76beebd382105446f4c71)
(Leaving this in draft until the big PR gets in; I just don't want to forget about this)
> Expand % pattern to expressions

- .pre-commit-config.yaml
- src/arch_mips.py
- src/if_statements.py
- src/main.py
- src/translate.py
- tests/ppc_disasm.py
As best as I can tell `bal` is nearly equivalent to `jal`,
with the difference being that `bal` can only be used if the
function being called is in the same file.
That is to say, `bal` indicates that the function being
called is position-independent code.
Also includes some formatting updates from black
Signed-off-by: Taggerung <tyler.taggerung@gmail.com>
> Add support for MIPS add, sub, and bal instructions

- src/arch_mips.py
- src/arch_ppc.py
- src/instruction.py
- src/ir_pattern.py
- src/translate.py
Add `Instruction.eval_fn` and set it in `Arch.parse(...)` to move instruction evaluation logic out of translate.py. 
I also refactored some of the `instrs_*` members: now they're only referenced in a single function, so they no longer need to be as generic. 
The only output changes from this PR are in the tracebacks for certain errors.
> Move instruction logic out of translate.py and into arch_*.py

- m2c/if_statements.py
Negative hex cases produce an invalid value like this:
```c
switch (temp_v1) {                          /* switch 3; irregular */
case 0x-1:                              /* switch 3 */
```
With this fix a proper negative value is emitted:
```c
switch (temp_v1) {                          /* switch 3; irregular */
case -0x1:                              /* switch 3 */
```
> Fix negative values for hex cases

- m2c/translate.py
- m2c_macros.h
- tests/end_to_end/error/manual-out.c
- tests/end_to_end/ps2/manual-out.c
Uses a variadic macro to ensure valid C syntax.
An alternative approach would be to emit either strings or comments within the macro, rather than unescaped C.
> Fix `M2C_ERROR` when the message contains a comma

- m2c/arch_ppc.py
Currently, indexed store update instructions give an error along the lines of
```c
// Error: Expected instruction argument to be of the form offset($register), but found $r3
// At instruction: stwux $r9, $r3, $r5
```
due to the call of `a.memory_ref` in the eval_fn (which is only valid for the non-indexed versions).
This PR fixes this by splitting out the eval_fn into separate ones for the indexed and non-indexed versions like load update instructions do
One thing that's worth noting is that none of the current tests contain any of these instructions, and #187 doesn't actually list them; Super Paper Mario has some functions using the instructions if that helps (possibly means that only later CW versions actually emitted them)
> Fix ppc store update instructions

- m2c/evaluate.py
- tests/end_to_end/gcc-division/mwcc-o4p-out.c
The final if statement of fold_divmod also assumes that right_expr will be the literal, which MWCC doesn't always follow. Currently a MULT_HI extracted from `MULT_HI(x, N) >> M` would be normalised to fix this, but if original_expr was the MULT_HI then it might not be in order. Fixing this removes a large chunk of the test failures for MWCC.
Afaik all remaining failures for finding MWCC divisions come down to three things, which I don't think I understand the maths well enough to fix:
- Denominators generated are exceeding `(1 << 29)`, which blocks the translation of `((x / N) + ((x / N) >> 31)) --> x / N`
- MWCC also uses inner subtraction in negative divisions
- The `round_div` fails for the MULT_HI constants used in -4 and -7
> fold_divmod mwcc mult_hi ordering fix

- m2c/arch_mips.py
- m2c/types.py
- tests/end_to_end/ps2/manual-out.c
- tests/end_to_end/ps2/manual_mwcc-out.c
- tests/end_to_end/ps2/manual_mwcc.s
Compilers like MWCC 2.3 fairly commonly, and since they are kinda simple I thought it would be good to have them
- `paddub`: Behaves like `addu` but for quad registers. From what I have seen it is mostly used as a `move`
- `sq`/`lq`: Those behave like `sw` and `lw` but for quad registers. Most commonly used to save registers into the stack
> Add support for PS2's `paddub` and `sq`/`lq` instructions

- m2c/arch_mips.py
- m2c/evaluate.py
- tests/end_to_end/seb-seh/seb-mwcc-out.c
- tests/end_to_end/seb-seh/seb-mwcc.s
- tests/end_to_end/seb-seh/seh-mwcc-out.c
- tests/end_to_end/seb-seh/seh-mwcc.s
These instructions are found specifically on PlayStation Portable and they are backported to its processor from the mips32r2 specs.
`SEH` is a single instruction that replaces the combo `sll DST_REG, SRC_REG, 0x10` and `sra DST_REG, DST_REG, 0x10` to perform a `s16` cast. Same concept for `SEB` but when a cast to `s8` is required.
> Add support for `seb`/`seh` instructions from mips32r2

- README.md
- pyproject.toml
Currently, downstream users have to invoke some kind of Python script directly in order to run the CLI. This requires them to either write their own `m2c.py` wrapper script to invoke `m2c.main:main`, or manually download the repository (usually as a Git submodule).
This PR adds a freestanding command entrypoint, `m2c`, which can be run to invoke the `m2c` CLI simply by installing the Python package. This should streamline usage and dependency management for downstream users who don't use `m2c` as a library.
> pyproject.toml: Add `m2c` entrypoint when installed as package

- m2c/asm_file.py
- m2c/flow_graph.py
[encounter/decomp-toolkit](https://github.com/encounter/decomp-toolkit) outputs assembly files that are currently not fully compatible with m2c.
One problem is that labels have the format
```
.obj name, local
.float 0
.endobj name
```
This makes m2c not detect any data, bss, rodata or jump table labels.
Another problem is that jump tables have the prefix "jumptable_".
Ultimately, strings use the type ".string".
> Added compatibility for decomp-toolkit macros

- README.md
- m2c/if_statements.py
- m2c/main.py
- m2c/options.py
- m2c/translate.py
- website.py
These greatly help when decompiling Mario Party 4
> Add options to sort bss backwards and local variables descending by register number

- tests/add_test.py
The WINE variable was not initialized when the conditions weren't met, which caused an `UnboundLocalError`.
> Initialize WINE variable in add_test.py

- README.md
- m2c/c_types.py
This addresses a longstanding issue particularly affecting users trying to match Melee code on the m2c + decomp.me setup, where it's desirable to have the same context file able to both provide the correct type to m2c for the `user_data` of our custom `*_GObj` structs, as well as typedef the `*_GObj` structs back to `HSD_GObj`. Since it's undesirable to run a C preprocessor in m2c, a regular expression is used that mimics the functionality of an `#ifdef`, but only specific expressions are allowed to be used with it. Currently the only expression supported is hardcoded to be `M2CTX_DUAL`. Use of any other expression will raise a `Directives not supported yet` error like it currently does. The `#ifdef` also must contain an `#else` clause. For instance:
```c
#ifdef M2CTX_DUAL
typedef struct …
```
> Add a special `#ifdef` for decomp.me convenience

- m2c/arch_arm.py
- m2c/c_types.py
I'm not sure whether this could break in some other place, but it seems like the correct behavior to me.
> ARM: Fix subroutines getting appended with '/* extra? */' and 'Unable to find stack arg <offset> in block' for >= 4 args.
